# Generated by Django 3.0.7 on 2020-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20200820_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='CV',
            field=models.FileField(default='CV/default.png', upload_to='CV/'),
        ),
    ]
